// This file tests administrator and API-key repository queries against PostgreSQL.
package auth

import (
	"context"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/stark-lin/saturn/internal/platform/config"
	platformdb "github.com/stark-lin/saturn/internal/platform/db"
)

func TestSQLRepositoryWithPostgreSQL(t *testing.T) {
	databaseURL := os.Getenv("SATURN_TEST_DATABASE_URL")
	if strings.TrimSpace(databaseURL) == "" {
		t.Skip("set SATURN_TEST_DATABASE_URL to run PostgreSQL authentication repository test")
	}
	ctx := context.Background()
	handle, err := platformdb.Open(ctx, config.DatabaseConfig{URL: databaseURL})
	if err != nil {
		t.Fatalf("open database: %v", err)
	}
	t.Cleanup(func() { _ = handle.Close() })
	handle.DB.SetMaxOpenConns(1)
	if _, err := handle.DB.ExecContext(ctx, `
CREATE TEMPORARY TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    password_hash TEXT NOT NULL
);
CREATE TEMPORARY TABLE api_keys (
    ref_code TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    key_prefix TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    scopes TEXT[] NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ
)`); err != nil {
		t.Fatalf("create temporary auth tables: %v", err)
	}
	passwordHash, err := HashPassword("admin")
	if err != nil {
		t.Fatalf("hash password: %v", err)
	}
	repo := NewSQLRepository(handle.DB)
	if err := repo.CreateAdministratorIfMissing(ctx, "admin", passwordHash); err != nil {
		t.Fatalf("create administrator: %v", err)
	}
	administrator, err := repo.FindAdministratorByUsername(ctx, "admin")
	if err != nil || administrator.RefCode != AdministratorRefCode || !VerifyPassword(administrator.PasswordHash, "admin") {
		t.Fatalf("administrator = %#v, err = %v", administrator, err)
	}
	expiresAt := time.Now().UTC().Add(time.Hour)
	created, err := repo.CreateAPIKey(ctx, CreateAPIKeyRecord{
		RefCode: "KEY-4F8A2C10", Name: "saturn-mcp", KeyPrefix: "sat_sk_test",
		KeyHash: strings.Repeat("a", 64), Scopes: []ScopeName{ScopeDataRead}, ExpiresAt: &expiresAt,
	})
	if err != nil {
		t.Fatalf("create api key: %v", err)
	}
	if created.Name != "saturn-mcp" || len(created.Scopes) != 1 {
		t.Fatalf("created api key = %#v", created)
	}
	if _, err := repo.UseAPIKey(ctx, strings.Repeat("a", 64)); err != nil {
		t.Fatalf("use api key: %v", err)
	}
	revoked, err := repo.RevokeAPIKey(ctx, created.RefCode)
	if err != nil || revoked.RevokedAt == nil {
		t.Fatalf("revoked api key = %#v, err = %v", revoked, err)
	}
}
