// This file tests generated authentication repository queries against PostgreSQL.
package auth

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/stark-lin/go-proj/internal/platform/config"
	platformdb "github.com/stark-lin/go-proj/internal/platform/db"
)

func TestSQLRepositoryWithPostgreSQL(t *testing.T) {
	databaseURL := os.Getenv("SATURN_TEST_DATABASE_URL")
	if strings.TrimSpace(databaseURL) == "" {
		t.Skip("set SATURN_TEST_DATABASE_URL to run PostgreSQL authentication repository test")
	}

	ctx := context.Background()
	handle, err := platformdb.Open(ctx, config.DatabaseConfig{URL: databaseURL})
	if err != nil {
		t.Fatalf("open database: %v", err)
	}
	t.Cleanup(func() {
		if err := handle.Close(); err != nil {
			t.Fatalf("close database: %v", err)
		}
	})

	handle.DB.SetMaxOpenConns(1)
	if _, err := handle.DB.ExecContext(ctx, `
CREATE TEMPORARY TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    role TEXT NOT NULL,
    password_hash TEXT NOT NULL
)`); err != nil {
		t.Fatalf("create temporary users table: %v", err)
	}

	passwordHash, err := HashPassword("admin")
	if err != nil {
		t.Fatalf("hash password: %v", err)
	}
	repo := NewSQLRepository(handle.DB)
	if err := repo.CreateUserIfMissing(ctx, "admin", RoleSuperuser, passwordHash); err != nil {
		t.Fatalf("create user: %v", err)
	}
	if err := repo.CreateUserIfMissing(ctx, "admin", RoleUser, "replacement"); err != nil {
		t.Fatalf("create existing user: %v", err)
	}

	user, err := repo.FindUserByUsername(ctx, "admin")
	if err != nil {
		t.Fatalf("find user by username: %v", err)
	}
	if user.Role != RoleSuperuser || user.Email != "" || user.PasswordHash != passwordHash {
		t.Fatalf("user = %#v, want preserved superuser with empty email", user)
	}

	userByID, err := repo.FindUserByID(ctx, user.ID)
	if err != nil {
		t.Fatalf("find user by id: %v", err)
	}
	if userByID.Username != "admin" || userByID.Role != RoleSuperuser {
		t.Fatalf("user by id = %#v, want admin superuser", userByID)
	}

	aliceHash, err := HashPassword("secret")
	if err != nil {
		t.Fatalf("hash alice password: %v", err)
	}
	alice, err := repo.CreateUser(ctx, CreateUserRecord{
		Username:     "alice",
		Email:        "alice@example.com",
		Role:         RoleUser,
		PasswordHash: aliceHash,
	})
	if err != nil {
		t.Fatalf("create alice: %v", err)
	}
	if alice.ID == 0 || alice.Username != "alice" || alice.Email != "alice@example.com" || alice.Role != RoleUser {
		t.Fatalf("alice = %#v", alice)
	}
	if _, err := repo.CreateUser(ctx, CreateUserRecord{
		Username:     "alice",
		Role:         RoleUser,
		PasswordHash: aliceHash,
	}); !errors.Is(err, ErrUserConflict) {
		t.Fatalf("duplicate user error = %v, want conflict", err)
	}

	updatedAlice, err := repo.UpdateUserProfile(ctx, alice.ID, "alice2", "")
	if err != nil {
		t.Fatalf("update alice profile: %v", err)
	}
	if updatedAlice.Username != "alice2" || updatedAlice.Email != "" {
		t.Fatalf("updated alice = %#v", updatedAlice)
	}
	updatedAlice, err = repo.UpdateUserPassword(ctx, alice.ID, passwordHash)
	if err != nil {
		t.Fatalf("update alice password: %v", err)
	}
	if !VerifyPassword(updatedAlice.PasswordHash, "admin") {
		t.Fatalf("updated alice password hash does not verify")
	}
}
