// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package filessqlc

import (
	"context"
)

const listFileCollectionsAll = `-- name: ListFileCollectionsAll :many

SELECT c.id, c.owner_id, collection_ref.ref_code, c.name, c.description, collection_ref.status
FROM file_collections AS c
JOIN object_refs AS collection_ref
  ON collection_ref.owner_id = c.owner_id
 AND collection_ref.object_type = 'file_collection'
 AND collection_ref.object_id = c.id
ORDER BY c.created_at DESC, collection_ref.ref_code DESC
LIMIT $1 OFFSET $2
`

type ListFileCollectionsAllParams struct {
	Limit  int32
	Offset int32
}

type ListFileCollectionsAllRow struct {
	ID          int64
	OwnerID     int64
	RefCode     string
	Name        string
	Description string
	Status      string
}

// This file defines typed Files query templates for sqlc generation.
//
//	SELECT c.id, c.owner_id, collection_ref.ref_code, c.name, c.description, collection_ref.status
//	FROM file_collections AS c
//	JOIN object_refs AS collection_ref
//	  ON collection_ref.owner_id = c.owner_id
//	 AND collection_ref.object_type = 'file_collection'
//	 AND collection_ref.object_id = c.id
//	ORDER BY c.created_at DESC, collection_ref.ref_code DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListFileCollectionsAll(ctx context.Context, arg ListFileCollectionsAllParams) ([]ListFileCollectionsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listFileCollectionsAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFileCollectionsAllRow
	for rows.Next() {
		var i ListFileCollectionsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RefCode,
			&i.Name,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesAll = `-- name: ListFilesAll :many
SELECT f.id, f.owner_id, f.collection_id, file_ref.ref_code, collection_ref.ref_code AS collection_ref_code,
       f.original_name, f.mime_type, f.size_bytes, f.sha256, f.blake3, file_ref.status
FROM files AS f
JOIN object_refs AS file_ref
  ON file_ref.owner_id = f.owner_id
 AND file_ref.object_type = 'file'
 AND file_ref.object_id = f.id
JOIN file_collections AS c
  ON c.owner_id = f.owner_id
 AND c.id = f.collection_id
JOIN object_refs AS collection_ref
  ON collection_ref.owner_id = c.owner_id
 AND collection_ref.object_type = 'file_collection'
 AND collection_ref.object_id = c.id
ORDER BY f.created_at DESC, file_ref.ref_code DESC
LIMIT $1 OFFSET $2
`

type ListFilesAllParams struct {
	Limit  int32
	Offset int32
}

type ListFilesAllRow struct {
	ID                int64
	OwnerID           int64
	CollectionID      int64
	RefCode           string
	CollectionRefCode string
	OriginalName      string
	MimeType          string
	SizeBytes         int64
	Sha256            string
	Blake3            string
	Status            string
}

// ListFilesAll
//
//	SELECT f.id, f.owner_id, f.collection_id, file_ref.ref_code, collection_ref.ref_code AS collection_ref_code,
//	       f.original_name, f.mime_type, f.size_bytes, f.sha256, f.blake3, file_ref.status
//	FROM files AS f
//	JOIN object_refs AS file_ref
//	  ON file_ref.owner_id = f.owner_id
//	 AND file_ref.object_type = 'file'
//	 AND file_ref.object_id = f.id
//	JOIN file_collections AS c
//	  ON c.owner_id = f.owner_id
//	 AND c.id = f.collection_id
//	JOIN object_refs AS collection_ref
//	  ON collection_ref.owner_id = c.owner_id
//	 AND collection_ref.object_type = 'file_collection'
//	 AND collection_ref.object_id = c.id
//	ORDER BY f.created_at DESC, file_ref.ref_code DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListFilesAll(ctx context.Context, arg ListFilesAllParams) ([]ListFilesAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesAllRow
	for rows.Next() {
		var i ListFilesAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CollectionID,
			&i.RefCode,
			&i.CollectionRefCode,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.Blake3,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
