// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package auditsqlc

import (
	"context"
	"database/sql"
	"time"
)

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_logs (
    actor_type,
    actor_user_id,
    action,
    target_ref_code,
    result,
    reason,
    source_ip,
    user_agent
)
VALUES (
    $1::text::audit_actor_type,
    $2,
    $3::text::audit_action,
    $4,
    $5::text::audit_result,
    $6,
    $7::text::inet,
    $8
)
RETURNING id, actor_type::text AS actor_type, actor_user_id, action::text AS action,
          target_ref_code, result::text AS result, reason, source_ip::text AS source_ip,
          user_agent, created_at
`

type InsertAuditLogParams struct {
	ActorType     string
	ActorUserID   sql.NullInt64
	Action        string
	TargetRefCode string
	Result        string
	Reason        sql.NullString
	SourceIp      string
	UserAgent     sql.NullString
}

type InsertAuditLogRow struct {
	ID            int64
	ActorType     string
	ActorUserID   sql.NullInt64
	Action        string
	TargetRefCode string
	Result        string
	Reason        sql.NullString
	SourceIp      string
	UserAgent     sql.NullString
	CreatedAt     time.Time
}

// This file defines append-only audit log query templates for sqlc generation.
//
//	INSERT INTO audit_logs (
//	    actor_type,
//	    actor_user_id,
//	    action,
//	    target_ref_code,
//	    result,
//	    reason,
//	    source_ip,
//	    user_agent
//	)
//	VALUES (
//	    $1::text::audit_actor_type,
//	    $2,
//	    $3::text::audit_action,
//	    $4,
//	    $5::text::audit_result,
//	    $6,
//	    $7::text::inet,
//	    $8
//	)
//	RETURNING id, actor_type::text AS actor_type, actor_user_id, action::text AS action,
//	          target_ref_code, result::text AS result, reason, source_ip::text AS source_ip,
//	          user_agent, created_at
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRowContext(ctx, insertAuditLog,
		arg.ActorType,
		arg.ActorUserID,
		arg.Action,
		arg.TargetRefCode,
		arg.Result,
		arg.Reason,
		arg.SourceIp,
		arg.UserAgent,
	)
	var i InsertAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorUserID,
		&i.Action,
		&i.TargetRefCode,
		&i.Result,
		&i.Reason,
		&i.SourceIp,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_type::text AS actor_type, actor_user_id, action::text AS action,
       target_ref_code, result::text AS result, reason, source_ip::text AS source_ip,
       user_agent, created_at
FROM audit_logs
WHERE ($1::text = '' OR target_ref_code = $1)
  AND ($2::bigint = 0 OR actor_user_id = $2)
  AND ($3::text = '' OR action::text = $3)
  AND ($4::text = '' OR result::text = $4)
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListAuditLogsParams struct {
	TargetRefCode string
	ActorUserID   int64
	Action        string
	Result        string
	PageOffset    int32
	PageLimit     int32
}

type ListAuditLogsRow struct {
	ID            int64
	ActorType     string
	ActorUserID   sql.NullInt64
	Action        string
	TargetRefCode string
	Result        string
	Reason        sql.NullString
	SourceIp      string
	UserAgent     sql.NullString
	CreatedAt     time.Time
}

// ListAuditLogs
//
//	SELECT id, actor_type::text AS actor_type, actor_user_id, action::text AS action,
//	       target_ref_code, result::text AS result, reason, source_ip::text AS source_ip,
//	       user_agent, created_at
//	FROM audit_logs
//	WHERE ($1::text = '' OR target_ref_code = $1)
//	  AND ($2::bigint = 0 OR actor_user_id = $2)
//	  AND ($3::text = '' OR action::text = $3)
//	  AND ($4::text = '' OR result::text = $4)
//	ORDER BY created_at DESC, id DESC
//	LIMIT $6 OFFSET $5
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.TargetRefCode,
		arg.ActorUserID,
		arg.Action,
		arg.Result,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorUserID,
			&i.Action,
			&i.TargetRefCode,
			&i.Result,
			&i.Reason,
			&i.SourceIp,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
