-- This migration creates immutable Files collection and file tables.
CREATE TABLE file_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (BTRIM(name) <> ''),
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (owner_id, id)
);

CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    collection_id BIGINT NOT NULL,
    object_key TEXT NOT NULL,
    original_name TEXT NOT NULL CHECK (BTRIM(original_name) <> ''),
    mime_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    blake3 TEXT NOT NULL CHECK (blake3 ~ '^[0-9a-f]{64}$'),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (owner_id, collection_id)
        REFERENCES file_collections(owner_id, id)
        ON DELETE CASCADE,
    UNIQUE (owner_id, id),
    UNIQUE (owner_id, object_key)
);

CREATE FUNCTION reject_file_collection_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'file collections are immutable';
END;
$$;

CREATE TRIGGER file_collections_immutable
BEFORE UPDATE ON file_collections
FOR EACH ROW EXECUTE FUNCTION reject_file_collection_mutation();

CREATE FUNCTION reject_file_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'files are immutable';
END;
$$;

CREATE TRIGGER files_immutable
BEFORE UPDATE ON files
FOR EACH ROW EXECUTE FUNCTION reject_file_mutation();

CREATE INDEX idx_file_collections_owner_created
ON file_collections (owner_id, created_at DESC, id DESC);

CREATE INDEX idx_files_collection_created
ON files (collection_id, created_at DESC, id DESC);

CREATE INDEX idx_files_owner_created
ON files (owner_id, created_at DESC, id DESC);
