-- This migration creates platform search tables from the ER diagram.
CREATE TABLE search_documents (
    id TEXT PRIMARY KEY,
    object_ref_id BIGINT NOT NULL REFERENCES object_refs(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    resource_id BIGINT NOT NULL,
    ref_code TEXT,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status TEXT NOT NULL
);

CREATE TABLE search_index_queue_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_ref_id BIGINT NOT NULL REFERENCES object_refs(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    resource_id BIGINT NOT NULL,
    status TEXT NOT NULL
);

CREATE INDEX idx_search_documents_object_ref ON search_documents (object_ref_id);
