-- This migration creates Calendar event aggregate tables.
CREATE TABLE event_aggregates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    metadata JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (owner_id, id)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    aggregate_id BIGINT NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
    metadata JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'voided')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (owner_id, aggregate_id)
        REFERENCES event_aggregates(owner_id, id)
        ON DELETE CASCADE
);

CREATE FUNCTION reject_calendar_event_aggregate_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'calendar event aggregates are immutable';
END;
$$;

CREATE TRIGGER event_aggregates_immutable
BEFORE UPDATE ON event_aggregates
FOR EACH ROW EXECUTE FUNCTION reject_calendar_event_aggregate_mutation();

CREATE FUNCTION reject_calendar_event_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.owner_id IS DISTINCT FROM OLD.owner_id
       OR NEW.aggregate_id IS DISTINCT FROM OLD.aggregate_id
       OR NEW.starts_at IS DISTINCT FROM OLD.starts_at
       OR NEW.duration_minutes IS DISTINCT FROM OLD.duration_minutes
       OR NEW.metadata IS DISTINCT FROM OLD.metadata
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'calendar events are immutable except void status';
    END IF;

    IF NOT (OLD.status = 'scheduled' AND NEW.status = 'voided') THEN
        RAISE EXCEPTION 'calendar event status may only transition from scheduled to voided';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER events_immutable_except_void
BEFORE UPDATE ON events
FOR EACH ROW EXECUTE FUNCTION reject_calendar_event_mutation();

CREATE INDEX idx_event_aggregates_owner_created
ON event_aggregates (owner_id, created_at DESC, id DESC);

CREATE INDEX idx_events_owner_starts
ON events (owner_id, starts_at ASC, id ASC);

CREATE INDEX idx_events_aggregate_starts
ON events (aggregate_id, starts_at ASC, id ASC);

CREATE INDEX idx_events_owner_status_starts
ON events (owner_id, status, starts_at ASC, id ASC);
