-- This migration creates identity, object reference, tag, and audit tables from the ER diagram.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('superuser', 'user')),
    password_hash TEXT NOT NULL
);

CREATE SEQUENCE object_ref_code_sequence AS BIGINT
    START WITH 1
    MAXVALUE 4294967295
    NO CYCLE;

CREATE TABLE object_refs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ref_code TEXT NOT NULL UNIQUE CHECK (ref_code ~ '^[A-Z]{3}-[0-9A-F]{8}$'),
    object_type TEXT NOT NULL CHECK (object_type IN ('note', 'file_collection', 'file', 'event_aggregate', 'event', 'account', 'transaction', 'llm_session', 'llm_request')),
    object_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{}',
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (
        (object_type = 'note' AND ref_code LIKE 'NTE-%')
        OR (object_type IN ('file_collection', 'file') AND ref_code LIKE 'FIL-%')
        OR (object_type IN ('event_aggregate', 'event') AND ref_code LIKE 'CAL-%')
        OR (object_type IN ('account', 'transaction') AND ref_code LIKE 'ACC-%')
        OR (object_type IN ('llm_session', 'llm_request') AND ref_code LIKE 'LLM-%')
    ),
    UNIQUE (owner_id, object_type, object_id)
);

CREATE TYPE audit_actor_type AS ENUM ('USER', 'SYSTEM', 'LLM', 'ANONYMOUS');
CREATE TYPE audit_action AS ENUM ('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'LOGIN', 'LOGOUT');
CREATE TYPE audit_result AS ENUM ('SUCCESS', 'FAILED', 'DENIED');

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type audit_actor_type NOT NULL,
    actor_user_id BIGINT,
    action audit_action NOT NULL,
    target_ref_code TEXT NOT NULL CHECK (target_ref_code ~ '^[A-Z]{3}-[0-9A-F]{8}$'),
    result audit_result NOT NULL,
    reason TEXT,
    source_ip INET NOT NULL,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT audit_actor_user_rule CHECK (
        (actor_type = 'USER' AND actor_user_id IS NOT NULL)
        OR
        (actor_type IN ('SYSTEM', 'LLM', 'ANONYMOUS') AND actor_user_id IS NULL)
    ),
    CONSTRAINT audit_llm_read_rule CHECK (action <> 'READ' OR actor_type = 'LLM'),
    CONSTRAINT audit_system_auth_target_rule CHECK (
        action NOT IN ('LOGIN', 'LOGOUT') OR target_ref_code = 'SYS-00000000'
    )
);

CREATE FUNCTION reject_audit_log_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only';
END;
$$;

CREATE TRIGGER audit_logs_append_only
BEFORE UPDATE OR DELETE ON audit_logs
FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation();

CREATE TRIGGER audit_logs_no_truncate
BEFORE TRUNCATE ON audit_logs
FOR EACH STATEMENT EXECUTE FUNCTION reject_audit_log_mutation();

CREATE INDEX idx_object_refs_owner_status ON object_refs (owner_id, status);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at DESC);
CREATE INDEX idx_audit_logs_target_created ON audit_logs (target_ref_code, created_at DESC);
CREATE INDEX idx_audit_logs_actor_user_id ON audit_logs (actor_user_id);
CREATE INDEX idx_audit_logs_login_result_created ON audit_logs (action, result, created_at DESC);
CREATE INDEX idx_audit_logs_source_ip ON audit_logs (source_ip);
CREATE INDEX idx_object_refs_tags ON object_refs USING GIN (tags);