-- This migration upgrades Notes to stable logical objects with immutable version objects.
ALTER TABLE object_refs DROP CONSTRAINT object_refs_object_type_check;
ALTER TABLE object_refs DROP CONSTRAINT object_refs_check;

UPDATE object_refs
SET object_type = 'nte-obj'
WHERE object_type = 'note';

ALTER TABLE object_refs ADD CONSTRAINT object_refs_object_type_check CHECK (
    object_type IN (
        'nte-obj', 'version-obj',
        'file_collection', 'file',
        'event_aggregate', 'event',
        'account', 'transaction',
        'llm_session', 'llm_request'
    )
);

ALTER TABLE object_refs ADD CONSTRAINT object_refs_module_prefix_check CHECK (
    (object_type IN ('nte-obj', 'version-obj') AND ref_code LIKE 'NTE-%')
    OR (object_type IN ('file_collection', 'file') AND ref_code LIKE 'FIL-%')
    OR (object_type IN ('event_aggregate', 'event') AND ref_code LIKE 'CAL-%')
    OR (object_type IN ('account', 'transaction') AND ref_code LIKE 'ACC-%')
    OR (object_type IN ('llm_session', 'llm_request') AND ref_code LIKE 'LLM-%')
);

ALTER TABLE notes
    ADD COLUMN current_version_id BIGINT,
    ADD COLUMN deleted_at TIMESTAMPTZ;

CREATE TABLE note_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    parent_version_id BIGINT,
    version_number BIGINT NOT NULL CHECK (version_number > 0),
    title TEXT NOT NULL CHECK (BTRIM(title) <> ''),
    content TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'text/markdown' CHECK (BTRIM(content_type) <> ''),
    operation TEXT NOT NULL CHECK (operation IN ('create', 'update', 'restore')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (note_id, version_number),
    UNIQUE (note_id, id),
    FOREIGN KEY (note_id, parent_version_id)
        REFERENCES note_versions(note_id, id)
);

INSERT INTO note_versions (note_id, version_number, title, content, content_type, operation, created_at)
SELECT id, 1, title, markdown, 'text/markdown', 'create', created_at
FROM notes;

INSERT INTO object_refs (owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at)
SELECT
    n.owner_id,
    'NTE-' || UPPER(LPAD(TO_HEX(nextval('object_ref_code_sequence')), 8, '0')),
    'version-obj',
    v.id,
    v.title,
    logical_ref.tags,
    'immutable',
    v.created_at,
    v.created_at
FROM note_versions AS v
JOIN notes AS n ON n.id = v.note_id
JOIN object_refs AS logical_ref
  ON logical_ref.owner_id = n.owner_id
 AND logical_ref.object_type = 'nte-obj'
 AND logical_ref.object_id = n.id;

UPDATE notes AS n
SET current_version_id = v.id
FROM note_versions AS v
WHERE v.note_id = n.id
  AND v.version_number = 1;

ALTER TABLE notes
    ADD CONSTRAINT notes_current_version_fk
        FOREIGN KEY (id, current_version_id)
        REFERENCES note_versions(note_id, id);

CREATE OR REPLACE FUNCTION ensure_note_has_current_version() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM notes WHERE id = NEW.id)
       AND NOT EXISTS (
           SELECT 1
           FROM notes AS n
           JOIN note_versions AS v
             ON v.note_id = n.id
            AND v.id = n.current_version_id
           WHERE n.id = NEW.id
       ) THEN
        RAISE EXCEPTION 'notes must reference a current version';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER notes_require_current_version
AFTER INSERT OR UPDATE ON notes
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION ensure_note_has_current_version();

ALTER TABLE notes
    DROP COLUMN title,
    DROP COLUMN markdown;

CREATE OR REPLACE FUNCTION reject_note_version_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'note versions are immutable';
END;
$$;

CREATE TRIGGER note_versions_immutable
BEFORE UPDATE ON note_versions
FOR EACH ROW EXECUTE FUNCTION reject_note_version_mutation();

CREATE INDEX idx_notes_owner_updated
ON notes (owner_id, updated_at DESC, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX idx_note_versions_note_number
ON note_versions (note_id, version_number DESC);
