-- This migration creates the minimal immutable Accounting ledger.
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (BTRIM(name) <> ''),
    type TEXT NOT NULL DEFAULT 'default'
        CHECK (type IN ('default', 'cash', 'bank', 'credit_card', 'digital_wallet', 'stored_value', 'other')),
    currency TEXT NOT NULL DEFAULT 'AUD'
        CHECK (currency ~ '^[A-Z]{3}$'),
    opening_balance_cents BIGINT NOT NULL DEFAULT 0,
    balance_cents BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (owner_id, id)
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL,
    occurred_on DATE NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('income', 'expense', 'adjustment')),
    amount_cents BIGINT NOT NULL CHECK (amount_cents <> 0),
    title TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'posted' CHECK (status IN ('posted', 'voided')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (owner_id, account_id)
        REFERENCES accounts(owner_id, id)
        ON DELETE CASCADE,
    CHECK (
        (kind = 'income' AND amount_cents > 0)
        OR (kind = 'expense' AND amount_cents < 0)
        OR kind = 'adjustment'
    )
);

CREATE FUNCTION reject_accounting_transaction_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.owner_id IS DISTINCT FROM OLD.owner_id
       OR NEW.account_id IS DISTINCT FROM OLD.account_id
       OR NEW.occurred_on IS DISTINCT FROM OLD.occurred_on
       OR NEW.kind IS DISTINCT FROM OLD.kind
       OR NEW.amount_cents IS DISTINCT FROM OLD.amount_cents
       OR NEW.title IS DISTINCT FROM OLD.title
       OR NEW.note IS DISTINCT FROM OLD.note
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'accounting transactions are immutable';
    END IF;

    IF NOT (OLD.status = 'posted' AND NEW.status = 'voided') THEN
        RAISE EXCEPTION 'accounting transaction status may only transition from posted to voided';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER transactions_immutable_except_void
BEFORE UPDATE ON transactions
FOR EACH ROW EXECUTE FUNCTION reject_accounting_transaction_mutation();

CREATE INDEX idx_accounts_owner_created
ON accounts (owner_id, created_at DESC);

CREATE INDEX idx_transactions_owner_occurred
ON transactions (owner_id, occurred_on DESC, id DESC);

CREATE INDEX idx_transactions_account_occurred
ON transactions (account_id, occurred_on DESC, id DESC);

CREATE INDEX idx_transactions_account_status
ON transactions (account_id, status);
