-- This migration creates LLM session, request, and reference tables.
CREATE TABLE llm_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (BTRIM(title) <> ''),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (owner_id, id)
);

CREATE TABLE llm_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES llm_sessions(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL CHECK (BTRIM(prompt) <> ''),
    model TEXT NOT NULL CHECK (BTRIM(model) <> ''),
    max_tokens INTEGER NOT NULL CHECK (max_tokens > 0),
    context_json JSONB NOT NULL,
    request_json JSONB NOT NULL,
    response_status TEXT NOT NULL DEFAULT 'queued' CHECK (response_status IN ('queued', 'running', 'success', 'error')),
    content TEXT NOT NULL DEFAULT '',
    error_code TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    response_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    FOREIGN KEY (owner_id, session_id)
        REFERENCES llm_sessions(owner_id, id)
        ON DELETE CASCADE,
    UNIQUE (owner_id, id)
);

CREATE TABLE llm_request_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES llm_requests(id) ON DELETE CASCADE,
    object_ref_id BIGINT REFERENCES object_refs(id) ON DELETE SET NULL,
    ref_code TEXT NOT NULL CHECK (ref_code ~ '^[A-Z]{3}-[0-9A-F]{8}$'),
    module TEXT NOT NULL,
    object_type TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (request_id, ref_code)
);

CREATE FUNCTION reject_llm_request_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF COALESCE(current_setting('saturn.deleting_llm_session', true), '') <> 'on' THEN
            RAISE EXCEPTION 'llm requests can only be deleted by deleting their session';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.response_status IN ('success', 'error') THEN
        RAISE EXCEPTION 'llm request response is terminal after first write';
    END IF;

    IF NEW.owner_id IS DISTINCT FROM OLD.owner_id
       OR NEW.session_id IS DISTINCT FROM OLD.session_id
       OR NEW.prompt IS DISTINCT FROM OLD.prompt
       OR NEW.model IS DISTINCT FROM OLD.model
       OR NEW.max_tokens IS DISTINCT FROM OLD.max_tokens
       OR NEW.context_json IS DISTINCT FROM OLD.context_json
       OR NEW.request_json IS DISTINCT FROM OLD.request_json
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'llm request identity is immutable';
    END IF;

    IF NEW.response_status NOT IN ('running', 'success', 'error') THEN
        RAISE EXCEPTION 'llm request response status may only transition to running, success or error';
    END IF;

    IF OLD.response_status = 'running' AND NEW.response_status = 'running' THEN
        RAISE EXCEPTION 'llm request response is already running';
    END IF;

    IF OLD.response_status = 'queued' AND NEW.response_status = 'running' THEN
        IF NEW.content IS DISTINCT FROM OLD.content
           OR NEW.error_code IS DISTINCT FROM OLD.error_code
           OR NEW.error_message IS DISTINCT FROM OLD.error_message
           OR NEW.response_json IS DISTINCT FROM OLD.response_json
           OR NEW.completed_at IS DISTINCT FROM OLD.completed_at THEN
            RAISE EXCEPTION 'llm request running transition cannot write response result';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.response_status <> 'running' THEN
        RAISE EXCEPTION 'llm request response must transition through running';
    END IF;

    IF NEW.response_status NOT IN ('success', 'error') THEN
        RAISE EXCEPTION 'llm request response status may only finish as success or error';
    END IF;

    IF NEW.response_status = 'error' AND BTRIM(NEW.error_message) = '' THEN
        RAISE EXCEPTION 'llm request error response requires an error message';
    END IF;

    IF NEW.completed_at IS NULL THEN
        RAISE EXCEPTION 'llm request response completion time is required';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER llm_requests_single_response_write
BEFORE UPDATE OR DELETE ON llm_requests
FOR EACH ROW EXECUTE FUNCTION reject_llm_request_mutation();

CREATE INDEX idx_llm_sessions_owner_created
ON llm_sessions (owner_id, created_at DESC, id DESC);

CREATE INDEX idx_llm_requests_session_created
ON llm_requests (session_id, created_at ASC, id ASC);

CREATE INDEX idx_llm_request_references_ref_code
ON llm_request_references (ref_code);
