-- This migration creates platform import, export, backup, and restore tables from the ER diagram.
CREATE TABLE import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status TEXT NOT NULL,
    manifest JSONB NOT NULL
);

CREATE TABLE export_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status TEXT NOT NULL,
    object_key TEXT NOT NULL
);

CREATE TABLE export_manifests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_job_id BIGINT NOT NULL REFERENCES export_jobs(id) ON DELETE CASCADE,
    manifest JSONB NOT NULL,
    checksum TEXT NOT NULL
);

CREATE TABLE restore_previews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    manifest JSONB NOT NULL,
    preview JSONB NOT NULL
);
