-- This migration creates identity, object reference, tag, and audit tables from the ER diagram.
CREATE TABLE users (
    id BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    ref_code TEXT NOT NULL UNIQUE CHECK (ref_code ~ '^USR-[0-9A-F]{8}$'),
    email TEXT UNIQUE,
    password_hash TEXT NOT NULL
);

CREATE TABLE api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code TEXT NOT NULL UNIQUE CHECK (ref_code ~ '^KEY-[0-9A-F]{8}$'),
    name TEXT NOT NULL UNIQUE CHECK (name ~ '^[a-z0-9][a-z0-9._-]{0,63}$'),
    key_prefix TEXT NOT NULL CHECK (key_prefix ~ '^sat_sk_[A-Za-z0-9_-]{8}$'),
    key_hash TEXT NOT NULL UNIQUE CHECK (key_hash ~ '^[0-9a-f]{64}$'),
    scopes TEXT[] NOT NULL CHECK (
        cardinality(scopes) > 0
        AND array_position(scopes, NULL) IS NULL
        AND scopes <@ ARRAY['data:read', 'data:write']::TEXT[]
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CHECK (expires_at IS NULL OR expires_at > created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE FUNCTION enforce_api_key_lifecycle() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' OR TG_OP = 'TRUNCATE' THEN
        RAISE EXCEPTION 'api keys cannot be physically deleted';
    END IF;

    IF NEW.ref_code IS DISTINCT FROM OLD.ref_code
       OR NEW.name IS DISTINCT FROM OLD.name
       OR NEW.key_prefix IS DISTINCT FROM OLD.key_prefix
       OR NEW.key_hash IS DISTINCT FROM OLD.key_hash
       OR NEW.scopes IS DISTINCT FROM OLD.scopes
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
        RAISE EXCEPTION 'api key identity and policy are immutable';
    END IF;

    IF OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at THEN
        RAISE EXCEPTION 'api key revocation is irreversible';
    END IF;

    IF NEW.last_used_at IS DISTINCT FROM OLD.last_used_at
       AND (NEW.last_used_at IS NULL OR (OLD.last_used_at IS NOT NULL AND NEW.last_used_at < OLD.last_used_at)) THEN
        RAISE EXCEPTION 'api key last-used time cannot move backwards';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER api_keys_lifecycle
BEFORE UPDATE OR DELETE ON api_keys
FOR EACH ROW EXECUTE FUNCTION enforce_api_key_lifecycle();

CREATE TRIGGER api_keys_no_truncate
BEFORE TRUNCATE ON api_keys
FOR EACH STATEMENT EXECUTE FUNCTION enforce_api_key_lifecycle();

CREATE SEQUENCE object_ref_code_sequence AS BIGINT
    START WITH 1
    MAXVALUE 4294967295
    NO CYCLE;

CREATE TABLE object_refs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL CHECK (owner_id >= 0),
    ref_code TEXT NOT NULL UNIQUE CHECK (ref_code ~ '^[A-Z]{3}-[0-9A-F]{8}$'),
    object_type TEXT NOT NULL CHECK (object_type IN ('user', 'api_key', 'note', 'file_collection', 'file', 'event_aggregate', 'event', 'account', 'transaction', 'llm_session', 'llm_request')),
    object_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{}',
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (
        (object_type = 'user' AND ref_code LIKE 'USR-%')
        OR (object_type = 'api_key' AND ref_code LIKE 'KEY-%')
        OR (object_type = 'note' AND ref_code LIKE 'NTE-%')
        OR (object_type IN ('file_collection', 'file') AND ref_code LIKE 'FIL-%')
        OR (object_type IN ('event_aggregate', 'event') AND ref_code LIKE 'CAL-%')
        OR (object_type IN ('account', 'transaction') AND ref_code LIKE 'ACC-%')
        OR (object_type IN ('llm_session', 'llm_request') AND ref_code LIKE 'LLM-%')
    ),
    CHECK (
        (object_type IN ('user', 'api_key') AND owner_id = 0)
        OR (object_type NOT IN ('user', 'api_key') AND owner_id > 0)
    ),
    UNIQUE (owner_id, object_type, object_id)
);

CREATE TYPE audit_action AS ENUM ('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'LOGIN', 'LOGOUT');
CREATE TYPE audit_result AS ENUM ('SUCCESS', 'FAILED', 'DENIED');

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_ref_code TEXT NOT NULL CHECK (
        actor_ref_code ~ '^USR-[0-9A-F]{8}$'
        OR actor_ref_code ~ '^KEY-[0-9A-F]{8}$'
        OR actor_ref_code = 'SYS-00000000'
    ),
    action audit_action NOT NULL,
    target_ref_code TEXT NOT NULL CHECK (
        target_ref_code ~ '^(USR|NTE|FIL|ACC|CAL|LLM|KEY)-[0-9A-F]{8}$'
        OR target_ref_code = 'SYS-00000000'
    ),
    result audit_result NOT NULL,
    reason TEXT,
    source_ip INET NOT NULL,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT audit_system_auth_target_rule CHECK (
        action NOT IN ('LOGIN', 'LOGOUT') OR target_ref_code = 'SYS-00000000'
    )
);

CREATE FUNCTION reject_audit_log_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only';
END;
$$;

CREATE TRIGGER audit_logs_append_only
BEFORE UPDATE OR DELETE ON audit_logs
FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation();

CREATE TRIGGER audit_logs_no_truncate
BEFORE TRUNCATE ON audit_logs
FOR EACH STATEMENT EXECUTE FUNCTION reject_audit_log_mutation();

CREATE INDEX idx_object_refs_owner_status ON object_refs (owner_id, status);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at DESC);
CREATE INDEX idx_audit_logs_target_created ON audit_logs (target_ref_code, created_at DESC);
CREATE INDEX idx_audit_logs_actor_ref_code ON audit_logs (actor_ref_code, created_at DESC);
CREATE INDEX idx_audit_logs_login_result_created ON audit_logs (action, result, created_at DESC);
CREATE INDEX idx_audit_logs_source_ip ON audit_logs (source_ip);
CREATE INDEX idx_object_refs_tags ON object_refs USING GIN (tags);
