-- This migration creates platform local file storage metadata tables.
CREATE TABLE storage_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key TEXT NOT NULL UNIQUE,
    path TEXT NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    blake3 TEXT NOT NULL CHECK (blake3 ~ '^[0-9a-f]{64}$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE storage_diagnostics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checked_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    details JSONB NOT NULL
);
