// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storagesqlc

import (
	"time"
)

type StorageObject struct {
	ID        int64
	ObjectKey string
	Path      string
	SizeBytes int64
	Sha256    string
	Blake3    string
	CreatedAt time.Time
}
