// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: objects.sql

package storagesqlc

import (
	"context"
)

const deleteStorageObjectByKey = `-- name: DeleteStorageObjectByKey :exec
DELETE FROM storage_objects
WHERE object_key = $1
`

// DeleteStorageObjectByKey
//
//	DELETE FROM storage_objects
//	WHERE object_key = $1
func (q *Queries) DeleteStorageObjectByKey(ctx context.Context, objectKey string) error {
	_, err := q.db.ExecContext(ctx, deleteStorageObjectByKey, objectKey)
	return err
}

const findStorageObjectByKey = `-- name: FindStorageObjectByKey :one
SELECT id, object_key, path, size_bytes, sha256, blake3, created_at
FROM storage_objects
WHERE object_key = $1
`

// FindStorageObjectByKey
//
//	SELECT id, object_key, path, size_bytes, sha256, blake3, created_at
//	FROM storage_objects
//	WHERE object_key = $1
func (q *Queries) FindStorageObjectByKey(ctx context.Context, objectKey string) (StorageObject, error) {
	row := q.db.QueryRowContext(ctx, findStorageObjectByKey, objectKey)
	var i StorageObject
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Path,
		&i.SizeBytes,
		&i.Sha256,
		&i.Blake3,
		&i.CreatedAt,
	)
	return i, err
}

const saveStorageObject = `-- name: SaveStorageObject :exec

INSERT INTO storage_objects (object_key, path, size_bytes, sha256, blake3)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (object_key) DO UPDATE
SET path = EXCLUDED.path,
    size_bytes = EXCLUDED.size_bytes,
    sha256 = EXCLUDED.sha256,
    blake3 = EXCLUDED.blake3
`

type SaveStorageObjectParams struct {
	ObjectKey string
	Path      string
	SizeBytes int64
	Sha256    string
	Blake3    string
}

// This file defines typed storage metadata query templates for sqlc generation.
//
//	INSERT INTO storage_objects (object_key, path, size_bytes, sha256, blake3)
//	VALUES ($1, $2, $3, $4, $5)
//	ON CONFLICT (object_key) DO UPDATE
//	SET path = EXCLUDED.path,
//	    size_bytes = EXCLUDED.size_bytes,
//	    sha256 = EXCLUDED.sha256,
//	    blake3 = EXCLUDED.blake3
func (q *Queries) SaveStorageObject(ctx context.Context, arg SaveStorageObjectParams) error {
	_, err := q.db.ExecContext(ctx, saveStorageObject,
		arg.ObjectKey,
		arg.Path,
		arg.SizeBytes,
		arg.Sha256,
		arg.Blake3,
	)
	return err
}
