// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authsqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, role, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, username, COALESCE(email, '') AS email, role, password_hash
`

type CreateUserParams struct {
	Username     string
	Email        sql.NullString
	Role         string
	PasswordHash string
}

type CreateUserRow struct {
	ID           int64
	Username     string
	Email        string
	Role         string
	PasswordHash string
}

// CreateUser
//
//	INSERT INTO users (username, email, role, password_hash)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, username, COALESCE(email, '') AS email, role, password_hash
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const createUserIfMissing = `-- name: CreateUserIfMissing :exec
INSERT INTO users (username, role, password_hash)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO NOTHING
`

type CreateUserIfMissingParams struct {
	Username     string
	Role         string
	PasswordHash string
}

// CreateUserIfMissing
//
//	INSERT INTO users (username, role, password_hash)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (username) DO NOTHING
func (q *Queries) CreateUserIfMissing(ctx context.Context, arg CreateUserIfMissingParams) error {
	_, err := q.db.ExecContext(ctx, createUserIfMissing, arg.Username, arg.Role, arg.PasswordHash)
	return err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, username, COALESCE(email, '') AS email, role, password_hash
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID           int64
	Username     string
	Email        string
	Role         string
	PasswordHash string
}

// FindUserByID
//
//	SELECT id, username, COALESCE(email, '') AS email, role, password_hash
//	FROM users
//	WHERE id = $1
func (q *Queries) FindUserByID(ctx context.Context, id int64) (FindUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one

SELECT id, username, COALESCE(email, '') AS email, role, password_hash
FROM users
WHERE username = $1
`

type FindUserByUsernameRow struct {
	ID           int64
	Username     string
	Email        string
	Role         string
	PasswordHash string
}

// This file defines typed authentication user queries for sqlc generation.
//
//	SELECT id, username, COALESCE(email, '') AS email, role, password_hash
//	FROM users
//	WHERE username = $1
func (q *Queries) FindUserByUsername(ctx context.Context, username string) (FindUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsername, username)
	var i FindUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $1
WHERE id = $2
RETURNING id, username, COALESCE(email, '') AS email, role, password_hash
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int64
}

type UpdateUserPasswordRow struct {
	ID           int64
	Username     string
	Email        string
	Role         string
	PasswordHash string
}

// UpdateUserPassword
//
//	UPDATE users
//	SET password_hash = $1
//	WHERE id = $2
//	RETURNING id, username, COALESCE(email, '') AS email, role, password_hash
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET username = $1,
    email = $2
WHERE id = $3
RETURNING id, username, COALESCE(email, '') AS email, role, password_hash
`

type UpdateUserProfileParams struct {
	Username string
	Email    sql.NullString
	ID       int64
}

type UpdateUserProfileRow struct {
	ID           int64
	Username     string
	Email        string
	Role         string
	PasswordHash string
}

// UpdateUserProfile
//
//	UPDATE users
//	SET username = $1,
//	    email = $2
//	WHERE id = $3
//	RETURNING id, username, COALESCE(email, '') AS email, role, password_hash
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile, arg.Username, arg.Email, arg.ID)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}
