// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authsqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (ref_code, name, key_prefix, key_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
`

type CreateAPIKeyParams struct {
	RefCode   string
	Name      string
	KeyPrefix string
	KeyHash   string
	Scopes    []string
	ExpiresAt sql.NullTime
}

// CreateAPIKey
//
//	INSERT INTO api_keys (ref_code, name, key_prefix, key_hash, scopes, expires_at)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.RefCode,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		pq.Array(arg.Scopes),
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		pq.Array(&i.Scopes),
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAdministrator = `-- name: CreateAdministrator :one
INSERT INTO users (ref_code, password_hash)
VALUES ($1, $2)
RETURNING id, ref_code, COALESCE(email, '') AS email, password_hash
`

type CreateAdministratorParams struct {
	RefCode      string
	PasswordHash string
}

type CreateAdministratorRow struct {
	ID           int64
	RefCode      string
	Email        string
	PasswordHash string
}

// CreateAdministrator
//
//	INSERT INTO users (ref_code, password_hash)
//	VALUES ($1, $2)
//	RETURNING id, ref_code, COALESCE(email, '') AS email, password_hash
func (q *Queries) CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) (CreateAdministratorRow, error) {
	row := q.db.QueryRowContext(ctx, createAdministrator, arg.RefCode, arg.PasswordHash)
	var i CreateAdministratorRow
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const findAPIKeyByRefCode = `-- name: FindAPIKeyByRefCode :one
SELECT id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
FROM api_keys
WHERE ref_code = $1
`

// FindAPIKeyByRefCode
//
//	SELECT id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
//	FROM api_keys
//	WHERE ref_code = $1
func (q *Queries) FindAPIKeyByRefCode(ctx context.Context, refCode string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, findAPIKeyByRefCode, refCode)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		pq.Array(&i.Scopes),
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const findAdministrator = `-- name: FindAdministrator :one
SELECT id, ref_code, COALESCE(email, '') AS email, password_hash
FROM users
LIMIT 1
`

type FindAdministratorRow struct {
	ID           int64
	RefCode      string
	Email        string
	PasswordHash string
}

// FindAdministrator
//
//	SELECT id, ref_code, COALESCE(email, '') AS email, password_hash
//	FROM users
//	LIMIT 1
func (q *Queries) FindAdministrator(ctx context.Context) (FindAdministratorRow, error) {
	row := q.db.QueryRowContext(ctx, findAdministrator)
	var i FindAdministratorRow
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const findAdministratorByRefCode = `-- name: FindAdministratorByRefCode :one

SELECT id, ref_code, COALESCE(email, '') AS email, password_hash
FROM users
WHERE ref_code = $1
`

type FindAdministratorByRefCodeRow struct {
	ID           int64
	RefCode      string
	Email        string
	PasswordHash string
}

// This file defines typed administrator and API key queries for sqlc generation.
//
//	SELECT id, ref_code, COALESCE(email, '') AS email, password_hash
//	FROM users
//	WHERE ref_code = $1
func (q *Queries) FindAdministratorByRefCode(ctx context.Context, refCode string) (FindAdministratorByRefCodeRow, error) {
	row := q.db.QueryRowContext(ctx, findAdministratorByRefCode, refCode)
	var i FindAdministratorByRefCodeRow
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
FROM api_keys
ORDER BY created_at DESC, ref_code DESC
`

// ListAPIKeys
//
//	SELECT id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
//	FROM api_keys
//	ORDER BY created_at DESC, ref_code DESC
func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.RefCode,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			pq.Array(&i.Scopes),
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE ref_code = $1
RETURNING id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
`

// RevokeAPIKey
//
//	UPDATE api_keys
//	SET revoked_at = COALESCE(revoked_at, NOW())
//	WHERE ref_code = $1
//	RETURNING id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
func (q *Queries) RevokeAPIKey(ctx context.Context, refCode string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, revokeAPIKey, refCode)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		pq.Array(&i.Scopes),
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateAdministratorEmail = `-- name: UpdateAdministratorEmail :one
UPDATE users
SET email = $1
WHERE id = 1
RETURNING id, ref_code, COALESCE(email, '') AS email, password_hash
`

type UpdateAdministratorEmailRow struct {
	ID           int64
	RefCode      string
	Email        string
	PasswordHash string
}

// UpdateAdministratorEmail
//
//	UPDATE users
//	SET email = $1
//	WHERE id = 1
//	RETURNING id, ref_code, COALESCE(email, '') AS email, password_hash
func (q *Queries) UpdateAdministratorEmail(ctx context.Context, email sql.NullString) (UpdateAdministratorEmailRow, error) {
	row := q.db.QueryRowContext(ctx, updateAdministratorEmail, email)
	var i UpdateAdministratorEmailRow
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const updateAdministratorPassword = `-- name: UpdateAdministratorPassword :one
UPDATE users
SET password_hash = $1
WHERE id = 1
RETURNING id, ref_code, COALESCE(email, '') AS email, password_hash
`

type UpdateAdministratorPasswordRow struct {
	ID           int64
	RefCode      string
	Email        string
	PasswordHash string
}

// UpdateAdministratorPassword
//
//	UPDATE users
//	SET password_hash = $1
//	WHERE id = 1
//	RETURNING id, ref_code, COALESCE(email, '') AS email, password_hash
func (q *Queries) UpdateAdministratorPassword(ctx context.Context, passwordHash string) (UpdateAdministratorPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updateAdministratorPassword, passwordHash)
	var i UpdateAdministratorPasswordRow
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const useAPIKey = `-- name: UseAPIKey :one
UPDATE api_keys
SET last_used_at = GREATEST(COALESCE(last_used_at, '-infinity'::timestamptz), clock_timestamp())
WHERE key_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
RETURNING id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
`

// UseAPIKey
//
//	UPDATE api_keys
//	SET last_used_at = GREATEST(COALESCE(last_used_at, '-infinity'::timestamptz), clock_timestamp())
//	WHERE key_hash = $1
//	  AND revoked_at IS NULL
//	  AND (expires_at IS NULL OR expires_at > NOW())
//	RETURNING id, ref_code, name, key_prefix, key_hash, scopes, created_at, last_used_at, expires_at, revoked_at
func (q *Queries) UseAPIKey(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, useAPIKey, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.RefCode,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		pq.Array(&i.Scopes),
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
