// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package llmsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const listRequestsForSession = `-- name: ListRequestsForSession :many
SELECT request.id, request.owner_id, request.session_id, request_ref.id AS object_ref_id,
       request_ref.ref_code, request.prompt, request.model, request.max_tokens,
       request.context_json, request.request_json, request.response_status,
       request.content, request.error_code, request.error_message, request.response_json,
       request.created_at, request.updated_at, request.completed_at
FROM llm_requests AS request
JOIN object_refs AS request_ref
  ON request_ref.owner_id = request.owner_id
 AND request_ref.object_type = 'llm_request'
 AND request_ref.object_id = request.id
WHERE request.owner_id = $1
  AND request.session_id = $2
ORDER BY request.created_at ASC, request.id ASC
LIMIT $3 OFFSET $4
`

type ListRequestsForSessionParams struct {
	OwnerID   int64
	SessionID int64
	Limit     int32
	Offset    int32
}

type ListRequestsForSessionRow struct {
	ID             int64
	OwnerID        int64
	SessionID      int64
	ObjectRefID    int64
	RefCode        string
	Prompt         string
	Model          string
	MaxTokens      int32
	ContextJson    json.RawMessage
	RequestJson    json.RawMessage
	ResponseStatus string
	Content        string
	ErrorCode      string
	ErrorMessage   string
	ResponseJson   json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
}

// ListRequestsForSession
//
//	SELECT request.id, request.owner_id, request.session_id, request_ref.id AS object_ref_id,
//	       request_ref.ref_code, request.prompt, request.model, request.max_tokens,
//	       request.context_json, request.request_json, request.response_status,
//	       request.content, request.error_code, request.error_message, request.response_json,
//	       request.created_at, request.updated_at, request.completed_at
//	FROM llm_requests AS request
//	JOIN object_refs AS request_ref
//	  ON request_ref.owner_id = request.owner_id
//	 AND request_ref.object_type = 'llm_request'
//	 AND request_ref.object_id = request.id
//	WHERE request.owner_id = $1
//	  AND request.session_id = $2
//	ORDER BY request.created_at ASC, request.id ASC
//	LIMIT $3 OFFSET $4
func (q *Queries) ListRequestsForSession(ctx context.Context, arg ListRequestsForSessionParams) ([]ListRequestsForSessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsForSession,
		arg.OwnerID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsForSessionRow
	for rows.Next() {
		var i ListRequestsForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.SessionID,
			&i.ObjectRefID,
			&i.RefCode,
			&i.Prompt,
			&i.Model,
			&i.MaxTokens,
			&i.ContextJson,
			&i.RequestJson,
			&i.ResponseStatus,
			&i.Content,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ResponseJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByOwner = `-- name: ListSessionsByOwner :many

SELECT s.id, s.owner_id, session_ref.id AS object_ref_id, session_ref.ref_code,
       s.title, s.status, s.created_at, s.updated_at
FROM llm_sessions AS s
JOIN object_refs AS session_ref
  ON session_ref.owner_id = s.owner_id
 AND session_ref.object_type = 'llm_session'
 AND session_ref.object_id = s.id
WHERE s.owner_id = $1
ORDER BY s.created_at DESC, s.id DESC
LIMIT $2 OFFSET $3
`

type ListSessionsByOwnerParams struct {
	OwnerID int64
	Limit   int32
	Offset  int32
}

type ListSessionsByOwnerRow struct {
	ID          int64
	OwnerID     int64
	ObjectRefID int64
	RefCode     string
	Title       string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// This file defines typed LLM query templates for sqlc generation.
//
//	SELECT s.id, s.owner_id, session_ref.id AS object_ref_id, session_ref.ref_code,
//	       s.title, s.status, s.created_at, s.updated_at
//	FROM llm_sessions AS s
//	JOIN object_refs AS session_ref
//	  ON session_ref.owner_id = s.owner_id
//	 AND session_ref.object_type = 'llm_session'
//	 AND session_ref.object_id = s.id
//	WHERE s.owner_id = $1
//	ORDER BY s.created_at DESC, s.id DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListSessionsByOwner(ctx context.Context, arg ListSessionsByOwnerParams) ([]ListSessionsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByOwnerRow
	for rows.Next() {
		var i ListSessionsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ObjectRefID,
			&i.RefCode,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
