// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package accountingsqlc

import (
	"context"
	"time"
)

const listAccountsAll = `-- name: ListAccountsAll :many

SELECT a.id, a.owner_id, object_ref.ref_code, a.name, a.type, a.currency,
       a.opening_balance_cents, a.balance_cents, a.created_at, a.updated_at
FROM accounts AS a
JOIN object_refs AS object_ref
  ON object_ref.owner_id = a.owner_id
 AND object_ref.object_type = 'account'
 AND object_ref.object_id = a.id
ORDER BY a.updated_at DESC, object_ref.ref_code DESC
LIMIT $1 OFFSET $2
`

type ListAccountsAllParams struct {
	Limit  int32
	Offset int32
}

type ListAccountsAllRow struct {
	ID                  int64
	OwnerID             int64
	RefCode             string
	Name                string
	Type                string
	Currency            string
	OpeningBalanceCents int64
	BalanceCents        int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// This file defines typed minimal Accounting ledger query templates for sqlc generation.
//
//	SELECT a.id, a.owner_id, object_ref.ref_code, a.name, a.type, a.currency,
//	       a.opening_balance_cents, a.balance_cents, a.created_at, a.updated_at
//	FROM accounts AS a
//	JOIN object_refs AS object_ref
//	  ON object_ref.owner_id = a.owner_id
//	 AND object_ref.object_type = 'account'
//	 AND object_ref.object_id = a.id
//	ORDER BY a.updated_at DESC, object_ref.ref_code DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListAccountsAll(ctx context.Context, arg ListAccountsAllParams) ([]ListAccountsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsAllRow
	for rows.Next() {
		var i ListAccountsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RefCode,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.OpeningBalanceCents,
			&i.BalanceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsAll = `-- name: ListTransactionsAll :many
SELECT t.id, t.owner_id, transaction_ref.ref_code, account_ref.ref_code AS account_ref_code,
       t.occurred_on, t.kind, t.amount_cents, t.title, t.note, t.status, t.created_at, t.updated_at
FROM transactions AS t
JOIN object_refs AS transaction_ref
  ON transaction_ref.owner_id = t.owner_id
 AND transaction_ref.object_type = 'transaction'
 AND transaction_ref.object_id = t.id
JOIN object_refs AS account_ref
  ON account_ref.owner_id = t.owner_id
 AND account_ref.object_type = 'account'
 AND account_ref.object_id = t.account_id
ORDER BY t.occurred_on DESC, t.id DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsAllParams struct {
	Limit  int32
	Offset int32
}

type ListTransactionsAllRow struct {
	ID             int64
	OwnerID        int64
	RefCode        string
	AccountRefCode string
	OccurredOn     time.Time
	Kind           string
	AmountCents    int64
	Title          string
	Note           string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// ListTransactionsAll
//
//	SELECT t.id, t.owner_id, transaction_ref.ref_code, account_ref.ref_code AS account_ref_code,
//	       t.occurred_on, t.kind, t.amount_cents, t.title, t.note, t.status, t.created_at, t.updated_at
//	FROM transactions AS t
//	JOIN object_refs AS transaction_ref
//	  ON transaction_ref.owner_id = t.owner_id
//	 AND transaction_ref.object_type = 'transaction'
//	 AND transaction_ref.object_id = t.id
//	JOIN object_refs AS account_ref
//	  ON account_ref.owner_id = t.owner_id
//	 AND account_ref.object_type = 'account'
//	 AND account_ref.object_id = t.account_id
//	ORDER BY t.occurred_on DESC, t.id DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListTransactionsAll(ctx context.Context, arg ListTransactionsAllParams) ([]ListTransactionsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsAllRow
	for rows.Next() {
		var i ListTransactionsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RefCode,
			&i.AccountRefCode,
			&i.OccurredOn,
			&i.Kind,
			&i.AmountCents,
			&i.Title,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
