// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package notessqlc

import (
	"context"
)

const listNotesForOwner = `-- name: ListNotesForOwner :many

SELECT n.id, n.owner_id, object_ref.ref_code, n.title, object_ref.status
FROM notes AS n
JOIN object_refs AS object_ref
  ON object_ref.owner_id = n.owner_id
 AND object_ref.object_type = 'note'
 AND object_ref.object_id = n.id
WHERE n.owner_id = $1
ORDER BY n.id DESC
LIMIT $2 OFFSET $3
`

type ListNotesForOwnerParams struct {
	OwnerID int64
	Limit   int32
	Offset  int32
}

type ListNotesForOwnerRow struct {
	ID      int64
	OwnerID int64
	RefCode string
	Title   string
	Status  string
}

// This file defines typed Notes query templates for sqlc generation.
//
//	SELECT n.id, n.owner_id, object_ref.ref_code, n.title, object_ref.status
//	FROM notes AS n
//	JOIN object_refs AS object_ref
//	  ON object_ref.owner_id = n.owner_id
//	 AND object_ref.object_type = 'note'
//	 AND object_ref.object_id = n.id
//	WHERE n.owner_id = $1
//	ORDER BY n.id DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListNotesForOwner(ctx context.Context, arg ListNotesForOwnerParams) ([]ListNotesForOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotesForOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesForOwnerRow
	for rows.Next() {
		var i ListNotesForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RefCode,
			&i.Title,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
