// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package notessqlc

import (
	"context"
)

const listNotesAll = `-- name: ListNotesAll :many

SELECT n.id, n.owner_id, object_ref.ref_code, version_ref.ref_code AS current_version_ref,
       version.version_number, version.title, object_ref.status
FROM notes AS n
JOIN object_refs AS object_ref
  ON object_ref.owner_id = n.owner_id
 AND object_ref.object_type = 'nte-obj'
 AND object_ref.object_id = n.id
JOIN note_versions AS version ON version.id = n.current_version_id
JOIN object_refs AS version_ref
  ON version_ref.owner_id = n.owner_id
 AND version_ref.object_type = 'version-obj'
 AND version_ref.object_id = version.id
ORDER BY n.id DESC
LIMIT $1 OFFSET $2
`

type ListNotesAllParams struct {
	Limit  int32
	Offset int32
}

type ListNotesAllRow struct {
	ID                int64
	OwnerID           int64
	RefCode           string
	CurrentVersionRef string
	VersionNumber     int64
	Title             string
	Status            string
}

// This file defines typed Notes query templates for sqlc generation.
//
//	SELECT n.id, n.owner_id, object_ref.ref_code, version_ref.ref_code AS current_version_ref,
//	       version.version_number, version.title, object_ref.status
//	FROM notes AS n
//	JOIN object_refs AS object_ref
//	  ON object_ref.owner_id = n.owner_id
//	 AND object_ref.object_type = 'nte-obj'
//	 AND object_ref.object_id = n.id
//	JOIN note_versions AS version ON version.id = n.current_version_id
//	JOIN object_refs AS version_ref
//	  ON version_ref.owner_id = n.owner_id
//	 AND version_ref.object_type = 'version-obj'
//	 AND version_ref.object_id = version.id
//	ORDER BY n.id DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListNotesAll(ctx context.Context, arg ListNotesAllParams) ([]ListNotesAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotesAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesAllRow
	for rows.Next() {
		var i ListNotesAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RefCode,
			&i.CurrentVersionRef,
			&i.VersionNumber,
			&i.Title,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
