// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package refsqlc

import (
	"time"
)

type ObjectRef struct {
	ID         int64
	OwnerID    int64
	RefCode    string
	ObjectType string
	ObjectID   int64
	Title      string
	Tags       []string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
