// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: object_refs.sql

package refsqlc

import (
	"context"

	"github.com/lib/pq"
)

const deleteObjectRef = `-- name: DeleteObjectRef :exec
DELETE FROM object_refs
WHERE owner_id = $1
  AND object_type = $2
  AND object_id = $3
`

type DeleteObjectRefParams struct {
	OwnerID    int64
	ObjectType string
	ObjectID   int64
}

// DeleteObjectRef
//
//	DELETE FROM object_refs
//	WHERE owner_id = $1
//	  AND object_type = $2
//	  AND object_id = $3
func (q *Queries) DeleteObjectRef(ctx context.Context, arg DeleteObjectRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteObjectRef, arg.OwnerID, arg.ObjectType, arg.ObjectID)
	return err
}

const findObjectRefByCode = `-- name: FindObjectRefByCode :one
SELECT id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
FROM object_refs
WHERE ref_code = $1
`

// FindObjectRefByCode
//
//	SELECT id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
//	FROM object_refs
//	WHERE ref_code = $1
func (q *Queries) FindObjectRefByCode(ctx context.Context, refCode string) (ObjectRef, error) {
	row := q.db.QueryRowContext(ctx, findObjectRefByCode, refCode)
	var i ObjectRef
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RefCode,
		&i.ObjectType,
		&i.ObjectID,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentObjectRefsByOwner = `-- name: ListRecentObjectRefsByOwner :many
SELECT id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
FROM object_refs
WHERE owner_id = $1
ORDER BY updated_at DESC, ref_code DESC
LIMIT $2
`

type ListRecentObjectRefsByOwnerParams struct {
	OwnerID int64
	Limit   int32
}

// ListRecentObjectRefsByOwner
//
//	SELECT id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
//	FROM object_refs
//	WHERE owner_id = $1
//	ORDER BY updated_at DESC, ref_code DESC
//	LIMIT $2
func (q *Queries) ListRecentObjectRefsByOwner(ctx context.Context, arg ListRecentObjectRefsByOwnerParams) ([]ObjectRef, error) {
	rows, err := q.db.QueryContext(ctx, listRecentObjectRefsByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObjectRef
	for rows.Next() {
		var i ObjectRef
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RefCode,
			&i.ObjectType,
			&i.ObjectID,
			&i.Title,
			pq.Array(&i.Tags),
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextObjectRefSequence = `-- name: NextObjectRefSequence :one

SELECT nextval('object_ref_code_sequence')::bigint
`

// This file defines typed object reference query templates for sqlc generation.
//
//	SELECT nextval('object_ref_code_sequence')::bigint
func (q *Queries) NextObjectRefSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextObjectRefSequence)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const registerObjectRef = `-- name: RegisterObjectRef :one
INSERT INTO object_refs (
    owner_id,
    ref_code,
    object_type,
    object_id,
    title,
    tags,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
`

type RegisterObjectRefParams struct {
	OwnerID    int64
	RefCode    string
	ObjectType string
	ObjectID   int64
	Title      string
	Tags       []string
	Status     string
}

// RegisterObjectRef
//
//	INSERT INTO object_refs (
//	    owner_id,
//	    ref_code,
//	    object_type,
//	    object_id,
//	    title,
//	    tags,
//	    status
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
func (q *Queries) RegisterObjectRef(ctx context.Context, arg RegisterObjectRefParams) (ObjectRef, error) {
	row := q.db.QueryRowContext(ctx, registerObjectRef,
		arg.OwnerID,
		arg.RefCode,
		arg.ObjectType,
		arg.ObjectID,
		arg.Title,
		pq.Array(arg.Tags),
		arg.Status,
	)
	var i ObjectRef
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RefCode,
		&i.ObjectType,
		&i.ObjectID,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateObjectRefProjection = `-- name: UpdateObjectRefProjection :one
UPDATE object_refs
SET title = $4,
    tags = $5,
    status = $6,
    updated_at = NOW()
WHERE owner_id = $1
  AND object_type = $2
  AND object_id = $3
RETURNING id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
`

type UpdateObjectRefProjectionParams struct {
	OwnerID    int64
	ObjectType string
	ObjectID   int64
	Title      string
	Tags       []string
	Status     string
}

// UpdateObjectRefProjection
//
//	UPDATE object_refs
//	SET title = $4,
//	    tags = $5,
//	    status = $6,
//	    updated_at = NOW()
//	WHERE owner_id = $1
//	  AND object_type = $2
//	  AND object_id = $3
//	RETURNING id, owner_id, ref_code, object_type, object_id, title, tags, status, created_at, updated_at
func (q *Queries) UpdateObjectRefProjection(ctx context.Context, arg UpdateObjectRefProjectionParams) (ObjectRef, error) {
	row := q.db.QueryRowContext(ctx, updateObjectRefProjection,
		arg.OwnerID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Title,
		pq.Array(arg.Tags),
		arg.Status,
	)
	var i ObjectRef
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RefCode,
		&i.ObjectType,
		&i.ObjectID,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
